from dataclasses import dataclass
import itertools
from math import ceil
from numpy import nan
import pandas as pd
import re
import requests
from time import sleep
from tqdm import tqdm
from typing import Optional, Literal
import warnings

from .data_loader import Data_Loader, str2json, _url_error_msg, get_legacy_session, _process_date, _default_limit, _use_gpd_force, \
    _has_gpd, _clean_date_input, _filter_inaccurate_date_query, _is_annual_date_query
from ..datetime_parser import to_datetime
from ..exceptions import OPD_DataUnavailableError, OPD_arcgisAuthInfoError, OPD_TooManyRequestsError
from .. import log

if _has_gpd:
    import geopandas as gpd
    from shapely.geometry import Point

logger = log.get_logger()

class repeat_format(object):
    def __init__(self, string):
        self.string = string
        self.repeat = int(string.count('{}')/2)

    def __eq__(self, other) -> bool:
        return isinstance(other, repeat_format) and self.string == other.string

    def format(self, date_field, date):
        args = []
        for _ in range(self.repeat):
            args.extend([date_field, date])
        args = tuple(args)
        return self.string.format(*args)
      

class Arcgis(Data_Loader):
    """
    A class for accessing data from ArcGIS clients

    Parameters
    ----------
    url : str
        URL
    date_field : str
        Name of the column that contains the date
    max_record_count : int
        Maximum number of records that can be returned per request
    is_table : bool
        Indicates if dataset is a table. Tables do not have GPS data

    Methods
    -------
    load(date=None, nrows=None, offset=0, pbar=True)
        Load data for query
    get_count(date=None, where=None)
        Get number of records/rows generated by query
    get_years()
        Get years contained in data set
    """

    # Based on https://developers.arcgis.com/rest/services-reference/online/feature-layer.htm
    __max_maxRecordCount = 32000
    
    def __init__(self, url, date_field=None, query=None):
        '''Create Arcgis object

        Parameters
        ----------
        url : str
            URL for ArcGIS data
        date_field : str
            (Optional) Name of the column that contains the date
        query : str, dict
            (Optional) Additional query that will be added to each request
        '''

        # TODO: Store date format

        self._date_type = None  # Data type of date field
        self._date_format = None
        self.date_field = date_field
        self.query = str2json(query)

        # Table vs. Layer: https://developers.arcgis.com/rest/services-reference/enterprise/layer-feature-service-.htm
        # The layer resource represents a single feature layer or a nonspatial table in a feature service. 
        # A feature layer is a table or view with at least one spatial column.
        # For tables, it provides basic information about the table such as its ID, name, fields, types, and templates. 
        # For feature layers, in addition to the table information, it provides information such as its geometry type, min and max scales, and spatial reference.

        p = re.search(r"(MapServer|FeatureServer)/\d+", url)
        self.url = url[:p.span()[1]]

        # Get metadata
        meta = self.__request()

        if 'type' not in meta and meta['status']=='error':
            raise OPD_DataUnavailableError(self.url, meta['messages'], _url_error_msg.format(self.url))

        if "maxRecordCount" in meta:
            self.max_record_count = meta["maxRecordCount"] if meta['maxRecordCount']<self.__max_maxRecordCount else self.__max_maxRecordCount
        else:
            self.max_record_count = None

        if meta["type"]=="Feature Layer":
            self.is_table = False
        elif meta["type"]=="Table":
            self.is_table = True
        else:
            raise ValueError("Unexpected ArcGIS layer type: {}".format(meta["type"]))


    def isfile(self):
        '''Returns False to indicate that ArcGIS data is not file-based

        Returns
        -------
        False
        '''
        return False


    def get_count(self, date=None, *,  where=None, **kwargs):
        '''Get number of records for a Arcgis data request
        
        Parameters
        ----------
        date : int or a length 2 list of start and stop year(s), date string(s), and/or timestamp(s)
            (Optional) Define timespan of data to request count for:
                1. Request data for an entire year by inputting the year (i.e. 2023)
                2. Request data from a start year or datetime to a stop year or datetime using a length 2 list (i.e. [2021, '2023-02-01'] for start of 2021 to end of 2023-02-01)
        where : str
            (Optional) SQL where query
            
        Returns
        -------
        int
            Record count or number of rows in data request
        '''

        if pd.isnull(self.date_field) and date!=None:
            raise ValueError(f'The dataset at {self.url} has no date field and therefore, cannot be filtered by date')

        date = _clean_date_input(date)
        return self.__get_count(date, where, True)[0]
        

    def __get_count(self, date, where, throw_error):
        if self._last_count is not None and self._last_count[0]==(date,where):
            logger.debug("Request matches previous count request. Returning saved count.")
            record_count = self._last_count[1]
            where_query = self._last_count[2]
        else:
            where_query = self.__construct_where(date, where=where)

            if throw_error and date!=None and self.count_precision!='day'and not _is_annual_date_query(date):
                raise ValueError(f"Count is not accurate for date input {date}. "
                                 "Date field contains data in text format not date format "
                                 "and the text not formatted in a way that makes getting a count "
                                 "difficult without loading in the data. Either adjust the input to "
                                 "get_count to get a range of years instead of a range of dates or "
                                 "load in the data for the desired date range")
            
            record_count = self.__request(where=where_query, return_count=True)["count"]

        self._last_count = ((date,where), record_count, where_query)

        return record_count, where_query
    

    def __request(self, where=None, return_count=False, out_fields="*", out_type="json", offset=0, count=None, sp_ref=None, order_by_date=True):

        try:
            r=requests.get(self.url, params={'f':'json'})
            # TODO: This should be only done once?
            orderby = [x['name'] for x in r.json()['fields'] if 'OBJECTID' in x['name'].upper()][0]
        except:
            orderby = None
        
        # Running with no inputs or just an out_type will return metadata only
        url = self.url + "/"
        params = {}
        if where != None:
            url+="query"
            params["where"] = where
            params["outFields"] = out_fields
            if return_count:
                params["returnCountOnly"] = True
            else:
                # Don't add offset for returning record count. The maximum value returned appears to be the maxRecordCount not the total count of records.
                # If it's ever desired to get the record with an offset, recommend getting the record count without the offset and then subtracting the offset.
                params["resultOffset"] = offset
                if sp_ref!=None:
                    params["outSR"] = sp_ref
                if order_by_date and pd.notnull(self.date_field) and self._ineq_comp:
                    params["orderByFields"] = f'{self.date_field}, {orderby}' if orderby else self.date_field
                
            if count!=None:
                params["resultRecordCount"] = count

        params["f"] = out_type
        params["cacheHint"] = False

        logger.debug(f"Request data from {url}")
        for k,v in params.items():
            logger.debug(f"\t{k} = {v}")

        try:
            r = requests.get(url, params=params)
            r.raise_for_status()
        except requests.exceptions.SSLError as e:
            if "[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled" in str(e.args[0]):
                with get_legacy_session() as session:
                    r = session.get(url, params=params)
                    
                r.raise_for_status()
            elif "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed" in str(e.args[0]):
                raise OPD_DataUnavailableError(self.url, e.args, _url_error_msg.format(self.url))
            else:
                raise e
        except requests.HTTPError as e:
            if len(e.args)>0:
                if "503 Server Error" in e.args[0]:
                    raise OPD_DataUnavailableError(self.url, e.args, _url_error_msg.format(self.url))

            else: raise e
        except requests.exceptions.ConnectTimeout as e:
            raise OPD_DataUnavailableError(self.url, e.args, _url_error_msg.format(self.url))
        except Exception as e: 
            raise e

        try:
            result = r.json()
        except requests.exceptions.JSONDecodeError:
            # Just raising for now. May add additional messaging later
            # This case is occurring in Charlotte OIS-Incidents data when the where query has OR keyword
            raise

        if isinstance(result, dict) and len(result.keys()) and "error" in result:
            args = ()
            for k,v in result['error'].items():
                if not hasattr(v,'__len__') or len(v)>0:
                    v = v[0] if isinstance(v,list) and len(v)==1 else v
                    args += (k,v)
            raise OPD_DataUnavailableError(url, 'Error returned by ArcGIS query', *args, _url_error_msg.format(self.url))
        
        return result
    

    def __construct_where(self, date=None, where=None):
        where_query = " AND ".join([f"{k} = '{v}'" for k,v in self.query.items()]) if self.query else None
        if where:
            where_query = where_query + " AND " + where if where_query else where

        if date!=None:
            if self.date_field==None:
                raise ValueError(f'The dataset at {self.url} has no date field and therefore, cannot be filtered by date')
            
            where_query = self._build_date_query(date)
        elif not where_query:
            where_query = '1=1'

        return where_query

 
    def _build_date_query(self, date):
        # Determine format by getting some data
        data = None
        if not self._date_type:
            # Load in sample data to determine date type and date query format
            data = self.__request(where=f'{self.date_field} IS NOT NULL', out_fields=self.date_field, count=1000, order_by_date=False)
            self._date_type = data['fields'][0]['type']

        if self._date_type in ['esriFieldTypeDate','esriFieldTypeDateOnly']:
            where_query = self._build_date_query_date_type(date)
        elif self._date_type in ['esriFieldTypeInteger','esriFieldTypeDouble'] and \
            (self.date_field.lower()=='yr' or 'year' in self.date_field.lower()):
            if not _is_annual_date_query(date):
                raise ValueError('Date field only provides the year not the full date. Date filtering must be from the start of year to the end of one.')
            where_query = self._build_date_query_date_type(date, is_numeric_year=True)
        elif self._date_type=='esriFieldTypeString':
            if not self._date_format:
                self._find_string_type_date_query_format(data)
                
            where_query = self._build_string_type_date_query(date)
        else:
            raise NotImplementedError(f"Unknown field {self._date_type}")

        return where_query
    

    def _find_string_type_date_query_format(self, data):
        offset = 1000
        while True:
            if len(data['features'])==0:
                warnings.warn("No non-null dates found in dataset. Unable to determine date format in order to generate query")
                self._date_type = None  # Revert _date_type to indicate that 
                return None
                
            dates = [x['attributes'][self.date_field] for x in data['features']]
            dates = [x for x in dates if len(x.strip())>0]

            if len(dates)>0:
                break

            # Update data
            data = self.__request(where=f'{self.date_field} IS NOT NULL', out_fields=self.date_field, count=1000, offset=offset)
            offset+=offset  # Scaling step size to more quickly search for non-empty dates


        # [regex for pattern, Arcgis Pattern OR date delimiter (punctuation between numbers), whether to use inquality to do comparison,
            # OPTIONAL time delimiter]
        @dataclass
        class DateParseParams:
            regex_pattern: re.Pattern
            arcgis_pattern: Optional[str] = None
            ineq_comp: bool = False
            date_delim: str = ""
            full_date: bool = True
            year_digits: int = 4
            precision: Literal["day","month","year"] = 'day'

        matches = [
            DateParseParams(re.compile(r"^(19|20)\d{6}\b"), ineq_comp=True),  # YYYYMMDD
            DateParseParams(re.compile(r"^(19|20)\d{12}\b"), ineq_comp=True),  # YYYYMMDDHHMMSS
            DateParseParams(re.compile(r"^(19|20)\d{2}-\d{2}-\d{2}(\b|T)"), ineq_comp=True, date_delim="-"),  # YYYY-MM-DDThh:mm:ss
            DateParseParams(re.compile(r"^(19|20)\d{2}/\d{2}/\d{2}"), ineq_comp=True, date_delim="/"),  # YYYY/MM/DD
            DateParseParams(re.compile(r"^[A-Z][a-z]+ \d{1,2}, (19|20)\d{2}\b"), "{} LIKE '[A-Z]% [0-9][0-9], {}' OR {} LIKE '[A-Z]% [0-9], {}'"),  # Month DD, YYYY
            DateParseParams(re.compile(r"^\d{1,2}[-/]\d{1,2}[-/](19|20)\d{2}\b"),   ## M/D/YYYY, MM/D/YYYY, M/DD/YYYY, MM/DD/YYYY (or same thing with hyphens)
                "{} LIKE '%[/-]{}%'"),  # mm/dd/yyyy or mm-dd-yyyy
            DateParseParams(re.compile(r"^\d{1,2}[-/]\d{1,2}[-/]\d{2}\b"),
                "{} LIKE '_/_/{} %' OR {} LIKE '__/_/{} %' OR {} LIKE '_/__/{} %' OR {} LIKE '__/__/{} %' OR "
                "{} LIKE '_-_-{} %' OR {} LIKE '__-_-{} %' OR {} LIKE '_-__-{} %' OR {} LIKE '__-__-{} %' OR "
                "{} LIKE '_/_/{}' OR {} LIKE '__/_/{}' OR {} LIKE '_/__/{}' OR {} LIKE '__/__/{}' OR "
                "{} LIKE '_-_-{}' OR {} LIKE '__-_-{}' OR {} LIKE '_-__-{}' OR {} LIKE '__-__-{}'",  # M/D/YY, MM/D/YY, M/DD/YY, MM/DD/YY (or same thing with hyphens)
                year_digits=2),  # mm/dd/yy or mm-dd-yy
            DateParseParams(re.compile(r"^\d{4}[-/]\d{1,2}$"), "{} LIKE '{}[-/]%'", precision='month'),  # YYYY-MM or YYYY/M
            DateParseParams(re.compile(r"^\d{4}$"), "{} = '{}'", precision='year'),  # YYYY
            DateParseParams(re.compile(r"^\d{1,2}[-/]\d{4}$"), "{} LIKE '[0-9][0-9][-/]{}' OR {} LIKE '[0-9][-/]{}'", precision='month'),  # MM-YYYY or MM/YYYY
        ]

        # Find most likely pattern
        hi = 0.0
        idx = None
        for k, m in enumerate(matches):
            if (new:=sum([isinstance(x,str) and m.regex_pattern.search(x) != None for x in dates])/len(dates)) > hi:
                hi = new
                idx = k

        if hi < 0.9:
            raise ValueError("Unable to find date string pattern")
            
        self._date_format = matches[idx]
        self._ineq_comp = self._date_format.ineq_comp
        self.date_precision = self._date_format.precision
        self.count_precision = 'day' if self._ineq_comp else 'year'  # This may change later if finer precision is enable with string where searches


    def _build_string_type_date_query(self, date):
        if self._ineq_comp:
            where_query = self._build_date_query_date_type(date, self._date_format.date_delim)
        else:
            year = [str(x)[:4] for x in date]

            def format_year(year):
                year = str(year)
                return year[-2:] if self._date_format.year_digits == 2 else year
            
            formatter = repeat_format(self._date_format.arcgis_pattern)
            where_query = formatter.format(self.date_field, format_year(year[0]))
            for x in range(int(year[0])+1,int(year[1])+1):
                where_query = f"{where_query} or " + formatter.format(self.date_field, format_year(x))

        return where_query
    
    
    def _build_date_query_date_type(self, date, date_delim='-', is_numeric_year=False):
        start_date, stop_date = _process_date(date, is_date_string=self._date_type=='esriFieldTypeString')

        start_date = start_date.replace('-',date_delim)
        stop_date =   stop_date.replace('-',date_delim)

        self._ineq_comp = True
        if is_numeric_year:
            self.date_precision = 'year'
            self.count_precision = 'year'
            return f"{self.date_field} >= {start_date[:4]} AND  {self.date_field} <= {stop_date[:4]}"
        else:
            self.date_precision = 'day'
            self.count_precision = 'day'
            return f"{self.date_field} >= '{start_date}' AND  {self.date_field} <= '{stop_date}'"

            # # TODO: The below was originally required by San Jose crash data. Need to Check if if still does or if any other dataset does
            # # This is the recommended way but it has been found to not work sometimes. One dataset was found that requires this.
            # # https://gis.stackexchange.com/questions/451107/arcgis-rest-api-unable-to-complete-operation-on-esrifieldtypedate-in-query
            # stop_date_tmp = stop_date.replace("T"," ")
            # where_query = f"{self.date_field} >= TIMESTAMP '{start_date}' AND  {self.date_field} < TIMESTAMP '{stop_date_tmp}'"


    def load(self, date=None, nrows=None, offset=0, *, pbar=True, format_date=True, **kwargs):
        '''Download table from ArcGIS to pandas or geopandas DataFrame
        
        Parameters
        ----------
        date : int or a length 2 list of start and stop year(s), date string(s), and/or timestamp(s)
            (Optional) Define timespan of data to request count for:
                1. Request data for an entire year by inputting the year (i.e. 2023)
                2. Request data from a start year or datetime to a stop year or datetime using a length 2 list (i.e. [2021, '2023-02-01'] for start of 2021 to end of 2023-02-01)
        nrows : int
            (Optional) Only returns the first nrows rows of the table
        offset - int
            (Optional) Number of records to offset from first record. Default is 0 to return records starting from the first.
        pbar : bool
            (Optional) If true (default), a progress bar will be displayed
        format_date : bool, optional
            If True, known date columns (based on presence of date_field in datasets table or data type information provided by dataset owner) will be automatically formatted
            to be pandas datetimes (or pandas Period in rare cases), by default True
            
        Returns
        -------
        pandas or geopandas DataFrame
            DataFrame containing table imported from ArcGIS
        '''

        if pd.isnull(self.date_field) and date!=None:
            raise ValueError(f'The dataset at {self.url} has no date field and therefore, cannot be filtered by date')

        date = _clean_date_input(date)
        
        record_count, where_query = self.__get_count(date, None, False)

        not_precise = date!=None and self.count_precision != 'day' and not _is_annual_date_query(date)
        if not_precise:
            if self.date_precision!='day':
                raise ValueError('Date field only provides the year and/or month, not the full date. In these, date filtering must currently be from the start of year to the end of one.')
            nrows_after_read = nrows
            offset_after_read = offset
            offset = 0
        
        # Update record count for request record offset
        record_count-=offset
        if record_count<=0:
            return pd.DataFrame()

        if nrows==None or nrows > record_count or not_precise:
            nrows = record_count
            
        batch_size = self.max_record_count or _default_limit
        batch_size = nrows if nrows < batch_size else batch_size
        num_batches = ceil(nrows / batch_size)
            
        pbar = pbar and num_batches>1
        if pbar:
            bar = tqdm(desc=self.url, total=nrows, leave=False) 
            
        features = []
        for batch in range(num_batches):
            bs = batch_size if batch<num_batches-1 else nrows-batch*batch_size
            try:
                try:
                    max_tries = 1 + (batch==0 and num_batches>1)
                    for k in range(max_tries):
                        data = self.__request(where=where_query, offset=offset+batch*batch_size, count=bs)
                        if len(data['features'])==batch_size:
                            break
                        elif k+1<max_tries:
                            sleep(2)  # https://maps2.dcgis.dc.gov/dcgis/rest/services/FEEDS/MPD/MapServer/35 has returned 1000 before when it should return 2000
                except:
                    if batch>0:
                        # There may have been an error due to too many requests over a short time. Wait and try again
                        sleep(10)
                        data = self.__request(where=where_query, offset=offset+batch*batch_size, count=bs)
                    else:
                        raise

                features.extend(data["features"])

                if batch==0:
                    date_cols = [x["name"] for x in data["fields"] if x["type"]=='esriFieldTypeDate' and x['name'].lower()!='time']
                    if not self.is_table:
                        wkid = data["spatialReference"]["wkid"]
                    if len(data["features"]) not in [batch_size, nrows]:
                        num_rows = len(data["features"])
                        raise ValueError(f"Number of rows is {num_rows} but is expected to be max rows to read {batch_size} or total number of rows {nrows}")
            except Exception as e:
                if len(e.args)>0 and "Error Code: 429" in e.args[0]:
                    raise OPD_TooManyRequestsError(self.url, *e.args, _url_error_msg.format(self.url))
                else:
                    raise
            except:
                raise

            if pbar:
                bar.update(len(data["features"]))

        if pbar:
            bar.close()

        df = pd.DataFrame.from_records([x["attributes"] for x in features])
        if format_date:
            for col in date_cols:
                if col in df:
                    logger.debug(f"Column {col} had a data type of esriFieldTypeDate. Converting values to datetime objects.")
                    df[col] = to_datetime(df[col], unit="ms", errors='coerce')

        if not_precise:
            df['tmp_idx'] = range(0,len(df))
            df = _filter_inaccurate_date_query(df, self.date_field, date, format_date, offset_after_read, nrows_after_read)
            features = [x for k,x in enumerate(features) if k in df['tmp_idx']]
            df = df.drop(columns='tmp_idx')

        if len(df) > 0:
            has_point_geometry = any("geometry" in x and "x" in x["geometry"] for x in features)
            if not self.is_table and has_point_geometry:
                if _use_gpd_force is not None:
                    if not _has_gpd and _use_gpd_force:
                        raise ValueError("User cannot force GeoPandas usage when it is not installed")
                    use_gpd = _use_gpd_force
                else:
                    use_gpd = _has_gpd

                if use_gpd:
                    # pyproj installs with geopandas
                    from pyproj.exceptions import CRSError
                    from pyproj import CRS

                    geometry = []
                    for feat in features:
                        if "geometry" not in feat:
                            geometry.append(None)
                        elif feat["geometry"]["x"]=="NaN":
                            geometry.append(Point(nan, nan))
                        else:
                            geometry.append(Point(feat["geometry"]["x"], feat["geometry"]["y"]))

                    logger.debug("Geometry found. Contructing geopandas GeoDataFrame")
                    try:
                        df = gpd.GeoDataFrame(df, crs=wkid, geometry=geometry)
                    except CRSError:
                        # CRS input method recommended by pyproj team to deal with CRSError for wkid = 102685
                        crs = CRS.from_authority("ESRI", wkid)
                        df = gpd.GeoDataFrame(df, crs=crs, geometry=geometry)
                    except Exception as e:
                        raise e
                else:
                    geometry = [feat["geometry"] if "geometry" in feat else None for feat in features]

                    if "geolocation" not in df:
                        logger.debug("Adding geometry column generated from spatial data provided by request.")
                        df["geolocation"] = geometry

            return df
        else:
            return pd.DataFrame()
