from math import ceil
import os
import warnings
import pandas as pd
from numpy import nan
import requests
from sodapy import Socrata as SocrataClient
from tqdm import tqdm
import re

from .data_loader import Data_Loader, _process_date, _url_error_msg, _use_gpd_force, _has_gpd, _clean_date_input, \
    _filter_inaccurate_date_query, _setup_records_request, _is_annual_date_query
from . import data_loader
from ..exceptions import OPD_SocrataHTTPError
from .. import log, datetime_parser

if _has_gpd:
    import geopandas as gpd

logger = log.get_logger()

# This is for use if import data sets using Socrata. It is not required.
# Requests made without an app_token will be subject to strict throttling limits
# Get a App Token here: http://dev.socrata.com/docs/app-tokens.html
# Copy the App Token
# Create an environment variable SODAPY_API_KEY and set it equal to the API key
# Setting environment variable in Linux: https://phoenixnap.com/kb/linux-set-environment-variable
# Windows: https://www.wikihow.com/Create-an-Environment-Variable-in-Windows-10
default_sodapy_key = os.environ.get("SODAPY_API_KEY")

class Socrata(Data_Loader):
    """
    A class for accessing data from Socrata clients

    Parameters
    ----------
    url : str
        URL of data homepage
    data_set : str
        Dataset ID
    date_field : str
        Name of the column that contains the date
    client : sodapy.Socrata
        Socrata client

    Methods
    -------
    load(date=None, nrows=None, offset=0, pbar=True, opt_filter=None, select=None, output_type=None)
        Load data for query
    get_count(date=None, opt_filter=None, where=None)
        Get number of records/rows generated by query
    get_years()
        Get years contained in data set
    """

    def __init__(self, url, data_set, date_field=None, key=default_sodapy_key):
        '''Create Socrata object

        Parameters
        ----------
        url : str
            URL for Socrata data
        data_set : str
            Dataset ID for Socrata data
        date_field : str
            (Optional) Name of the column that contains the date
        key : str
            (Optional) Socrata app token to prevent throttling of the data request
        '''
        self.url = url
        self.data_set = data_set
        self.date_field = date_field
        self.date_format = None
        # Unauthenticated client only works with public data sets. Note 'None'
        # in place of application token, and no username or password:
        self.client = SocrataClient(self.url, key, timeout=90)


    def __construct_where(self, date, opt_filter):
        where = ""
        if self.date_field!=None and date!=None:
            start_date, stop_date = _process_date(date)
            data_type, date_formats = self.__date_format_search(start_date, stop_date)

            if data_type=='timestamp' or date_formats=={'yyyymmdd'}:
                where = self.date_field + " between '" + start_date + "' and '" + stop_date +"'"
            elif data_type=='numeric':
                assert date_formats=={'YYYY'}
                accurate = _is_annual_date_query(date[0])
                if not accurate:
                    raise ValueError('Only the year is provided in the date column. Unable to filter by specific dates. Please filter by full years.')
                where = self.date_field + " between '" + start_date[:4] + "' and '" + stop_date[:4] +"'"
                where = [data_loader.Where(where=where, accurate=accurate)]
            else:
                start_range, full_years, stop_range = datetime_parser.split_date_range(start_date, stop_date)
                where = self.year_where_query(full_years)
                if start_range or stop_range:
                    where = where+" OR " if len(where)>0 else ''
                    if any(x in ['YYYY Q'] for x in date_formats):
                        raise ValueError('Unable to filter by date. Filter by year instead. Dates for this dataset only provide the quarter an event occurred (e.g. 2025 Q1).')
                    if any(x in ['YYYY'] for x in date_formats):
                        raise ValueError('Unable to filter by date. Filter by year instead. Date column only provides the year.')
                    for x in date_formats:
                        if x=='yyyymmdd':
                            where+=f'({self.yyyymmdd_where_query(start_range, stop_range)}) OR '
                        elif x=='abbrev_month':
                            if start_range:
                                where+=f'({self.__month_abbrev_where_query(start_range)}) OR '
                            if stop_range:
                                where+=f'({self.__month_abbrev_where_query(stop_range)}) OR '
                        elif x=='MM/DD/YYYY':
                            if start_range:
                                where+=f'({self.__mmddyyyy_where_query(start_range)}) OR '
                            if stop_range:
                                where+=f'({self.__mmddyyyy_where_query(stop_range)}) OR '
                        elif x=='MM/DD/YY':
                            if start_range:
                                where+=f'({self.__mmddyyyy_where_query(start_range, numdigits=2)}) OR '
                            if stop_range:
                                where+=f'({self.__mmddyyyy_where_query(stop_range, numdigits=2)}) OR '
                        elif x=='YYYY Q':
                            if start_range:
                                where+=f'({self.__yyyyq_where_query(start_range)}) OR '
                            if stop_range:
                                where+=f'({self.__yyyyq_where_query(stop_range)}) OR '
                        else:
                            raise ValueError(f"Unknown filter type: {x}")
                        
                    where = [data_loader.Where(where=where[:-4], accurate=False)]

        where = [data_loader.Where(where=where)] if not isinstance(where, list) else where
        if opt_filter is not None:
            if not isinstance(opt_filter, list):
                opt_filter = [opt_filter]

            andStr = " AND "
            for filt in opt_filter:
                for k in range(len(where)):
                    where[k].where += andStr + filt

                if where[k].where[0:len(andStr)] == andStr:
                    where[k].where = where[k].where[len(andStr):]

        return where
    

    def isfile(self):
        '''Returns False to indicate that Socrata data is not file-based

        Returns
        -------
        False
        '''
        return False
    
    def get_api_url(self):
        url = self.url[:-1] if self.url.endswith('/') else self.url
        url = url if url.startswith('http') else 'https://'+url
        return f"{url}/resource/{self.data_set}.json"


    def get_count(self, date=None, *,  opt_filter=None, where=None, **kwargs):
        '''Get number of records for a Socrata data request
        
        Parameters
        ----------
        date : int or a length 2 list of start and stop year(s), date string(s), and/or timestamp(s)
            (Optional) Define timespan of data to request count for:
                1. Request data for an entire year by inputting the year (i.e. 2023)
                2. Request data from a start year or datetime to a stop year or datetime using a length 2 list (i.e. [2021, '2023-02-01'] for start of 2021 to end of 2023-02-01)
        opt_filter : str
            (Optional) Additional filter to apply to data (beyond any date filter specified by self.date_field and date)
        where: str
            (Optional) where statement for Socrata query. If None, where statement will be constructed from self.date_field, date, and opt_filter
            
        Returns
        -------
        int
            Record count or number of rows in data request
        '''

        if pd.isnull(self.date_field) and date!=None:
            raise ValueError(f'The dataset at {self.url} has no date field and therefore, cannot be filtered by date')

        where = self.__get_counts(date, opt_filter, where)
        return sum(w.count for w in where)


    def __get_counts(self, date=None, opt_filter=None, where=None):
        date = _clean_date_input(date)

        if where==None:
            where = self.__construct_where(date, opt_filter)

            if any(not w.accurate for w in where):
                raise ValueError(f"Count is not accurate for date input {date}. "
                                 "Date field contains data in text format not date format "
                                 "and the text not formatted in a way that makes getting a count "
                                 "possible without loading in the data. Either adjust the input to "
                                 "get_count to get a range of years instead of a range of dates or "
                                 "load in the data for the current date range")

        if data_loader._check_query_match_last(self._last_count, date, where, opt_filter):
            logger.debug("Request matches previous count request. Returning saved count.")
            return self._last_count[1]
        
        logger.debug(f"Request dataset {self.data_set} from {self.url}")
        logger.debug(f"\twhere={where}")
        logger.debug(f"\tselect=count(*)")

        for w in where:
            try:
                results = self.client.get(self.data_set, where=w.where, select="count(*)")
            except (requests.HTTPError, requests.exceptions.ReadTimeout, requests.ConnectionError) as e:
                raise OPD_SocrataHTTPError(self.url, self.data_set, *e.args, _url_error_msg.format(self.get_api_url()))
            except Exception as e: 
                if len(e.args)>0 and isinstance(e.args[0],str) and (e.args[0].startswith('Unknown response format: text/html') or \
                    "Read timed out" in e.args[0]):
                    raise OPD_SocrataHTTPError(self.url, self.data_set, *e.args, _url_error_msg.format(self.get_api_url()))
                else:
                    raise e  
                
            try:
                num_rows = float(results[0]["count"])
            except:
                num_rows = float(results[0]["count_1"]) # Value used in VT Shootings data

            w.count = int(num_rows)

        self._last_count = data_loader._update_last_count(self._last_count, date, where, opt_filter)

        return where


    def load(self, date=None, nrows=None, offset=0, *, pbar=True, opt_filter=None, select=None, output_type=None, sortby=None, 
             format_date=True, **kwargs):
        '''Download table from Socrata to pandas or geopandas DataFrame
        
        Parameters
        ----------
        date : int or a length 2 list of start and stop year(s), date string(s), and/or timestamp(s)
            (Optional) Define timespan of data to request count for:
                1. Request data for an entire year by inputting the year (i.e. 2023)
                2. Request data from a start year or datetime to a stop year or datetime using a length 2 list (i.e. [2021, '2023-02-01'] for start of 2021 to end of 2023-02-01)
        nrows : int
            (Optional) Only returns the first nrows rows of the table
        offset - int
            (Optional) Number of records to offset from first record. Default is 0 to return records starting from the first.
        pbar : bool
            (Optional) If true (default), a progress bar will be displayed
        opt_filter : str
            (Optional) Additional filter to apply to data (beyond any date filter specified by self.date_field and date)
        select : str
            (Optional) select statement to REST API
        output_type : str
            (Optional) Data type for the output. Allowable values: GeoDataFrame, DataFrame, set. Default: GeoDataFrame or DataFrame
        sortby : str
            (Optional) Columns to sort by. Allowable values: None (defaults to id) or "date"
        format_date : bool, optional
            If True, known date columns (based on presence of date_field in datasets table or data type information provided by dataset owner) will be automatically formatted
            to be pandas datetimes (or pandas Period in rare cases), by default True
            
        Returns
        -------
        pandas or geopandas DataFrame
            DataFrame containing table
        '''

        if pd.isnull(self.date_field) and date!=None:
            raise ValueError(f'The dataset at {self.url} has no date field and therefore, cannot be filtered by date')

        date = _clean_date_input(date)

        where = self.__construct_where(date, opt_filter)
        
        if _use_gpd_force is not None:
            if not _has_gpd and _use_gpd_force:
                raise ValueError("User cannot force GeoPandas usage when it is not installed")
            use_gpd = _use_gpd_force
        else:
            use_gpd = _has_gpd

        where = self.__get_counts(where=where)
        
        where, nrows_req, nrows_after_read, offset_after_read, offset = \
            _setup_records_request(where, nrows, offset, sortby, self.date_field)
        
        if len(where)==0:
            return pd.DataFrame()

        batch_sizes, num_batches = data_loader._split_batches(nrows_req)
        total_batches = sum(num_batches)
            
        show_pbar = pbar and total_batches>1 and select==None
        bar = tqdm(desc=f"URL: {self.url}, Dataset: {self.data_set}", total=total_batches, leave=False) if show_pbar else None

        order = None
        if select == None:
            if sortby=="date":
                if self.date_field:
                    order = self.date_field
                else:
                    warnings.warn("Date sorting was requested but no date field was provided. Resulting data will not be sorted by date")
                    sortby = ":id"
            elif sortby:
                order = sortby
            else:
                # order guarantees data order remains the same when paging
                # Order by date if available otherwise the data ID. 
                # https://dev.socrata.com/docs/paging.html#2.1
                order = ":id"

        for k in range(len(where)):
            df_cur, output_type = self._request_data(where[k].where, select, batch_sizes[k], offset if k==0 else 0, 
                                        nrows_req[k], order, use_gpd, output_type, bar, show_pbar)
            if k==0:
                df = df_cur
            else:
                df = pd.concat([df, df_cur], ignore_index=True)

        if any(not w.accurate for w in where):
            df = _filter_inaccurate_date_query(df, self.date_field, date, format_date, offset_after_read, nrows_after_read)
        elif isinstance(df, pd.DataFrame) and nrows is not None and len(df)>nrows:
            df = df.head(nrows).reset_index(drop=True)

        if show_pbar:
            bar.close()

        return df


    def year_where_query(self, full_years):
        where = ''
        for y in full_years:
            # %25 is % wildcard symbol
            if self.url=='data.bloomington.in.gov' and self.data_set=='gpr2-wqbb':
                # This dataset has a text date field and contains YYYY/MM/DD and MM/DD/YY formats
                yy = str(y)[2:]
                where+='('+self.date_field + f" LIKE '_/_/{yy}' OR " + \
                    self.date_field + f" LIKE '_/__/{yy}' OR " + \
                    self.date_field + f" LIKE '__/_/{yy}' OR " + \
                    self.date_field + f" LIKE '__/__/{yy}' OR " + \
                    self.date_field + rf" LIKE '%{y}%') OR "
            else:
                where+='('+self.date_field + rf" LIKE '%{y}%') OR "
        where = where[:-4]

        return where
    

    def yyyymmdd_where_query(self, start_range, stop_range):
        where = ''
        f = '%Y-%m-%d'
        if start_range:
            where = f"({self.date_field} between '{start_range[0].strftime(f)}' and '{start_range[1]}')" + " OR "
        if stop_range:
            where+= f"({self.date_field} between '{stop_range[0].strftime(f)}' and '{stop_range[1]}')"
        else:
            where = where[:-4]

        return where
    

    def __yyyyq_where_query(self, date_range):
        def gen_where(m, year):
            where=self.date_field + f" LIKE '{year} Q{ceil(m/3)}'"
                
            return where
        
        return self.__loop_over_date_range(date_range, gen_where)


    def __mmddyyyy_where_query(self, date_range, numdigits=4):  
        def gen_where(m, year):
            where=self.date_field + f" LIKE '{m}/_/{year}%' OR " + \
                    self.date_field + f" LIKE '{m}/__/{year}%'"
            if m<10:
                where+=" OR "+self.date_field + f" LIKE '{m:02d}/_/{year}%' OR " + \
                    self.date_field + f" LIKE '{m:02d}/__/{year}%'"
                
            return where
        
        return self.__loop_over_date_range(date_range, gen_where, numdigits=numdigits)
    

    def __month_abbrev_where_query(self, date_range):
        months = 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec'.split('|')

        def gen_where(m, year):
            return rf"{self.date_field} LIKE '%{months[m-1]}%'"
        
        where = self.__loop_over_date_range(date_range, gen_where)

        return where
    
    def __loop_over_date_range(self, date_range, fcn, numdigits=4):
        assert numdigits in [2,4]
        dt = date_range[0]
        stop = (date_range[1]+pd.DateOffset(months=1)).replace(day=1).floor('D')
        wherelist = []
        last_year = None
        while dt<stop:
            year = dt.year if numdigits==4 else dt.year%1000
            if year!=last_year:
                wherelist.append([self.date_field + rf" LIKE '%{year}%'", set()])
            last_year = year

            wherelist[-1][1].add(fcn(dt.month, year))

            dt+=pd.DateOffset(months=1)

        where = ''
        for w in wherelist:
            x = f'{w[0]} AND ({' OR '.join(w[1])})'
            if len(wherelist)>1:
                x = f'({x})'
            where+=x+' OR '

        return where[:-4]
        
    
    def _request_data(self, where, select, batch_size, offset, nrows, order, use_gpd, output_type, bar, show_pbar):
        results = [None]  # Initialize to len > 0 so while loop runs
        start_offset = offset
        while len(results) > 0:
            logger.debug(f"Request dataset {self.data_set} from {self.url}")
            logger.debug(f"\twhere={where}")
            logger.debug(f"\tselect={select}")
            logger.debug(f"\tlimit={batch_size}")
            logger.debug(f"\toffset={offset}")
            logger.debug(f"\torder={order}")
            try:
                results = self.client.get(self.data_set, where=where,
                    limit=batch_size,offset=offset, select=select, order=order)
            except requests.HTTPError as e:
                raise OPD_SocrataHTTPError(self.url, self.data_set, *e.args, _url_error_msg.format(self.get_api_url()))
            except Exception as e: 
                arg_str = None
                err = e
                while True:
                    if len(err.args):
                        if isinstance(err.args[0],str):
                            arg_str = err.args[0]
                            break
                        elif isinstance(err.args[0],Exception):
                            err = err.args[0]
                        else:
                            break
                    else:
                        break
                if arg_str and (arg_str=='Unknown response format: text/html' or \
                    "Read timed out" in arg_str):
                    raise OPD_SocrataHTTPError(self.url, self.data_set, *e.args, _url_error_msg.format(self.get_api_url()))
                else:
                    raise e

            if use_gpd and output_type==None:
                # Check for geo info
                for r in results:
                    if "geolocation" in r or "geocoded_column" in r:
                        output_type = "GeoDataFrame"
                        break

            if output_type == "set":
                if offset==start_offset:
                    df = set()

                if len(results)>0:
                    filt_key = select.replace("DISTINCT ", "")
                    results = [row[filt_key] for row in results if len(row)>0]
                    results = set(results)
                    df.update(results)

            elif output_type == "list":
                raise NotImplementedError('list option for output_type has been removed')
            elif use_gpd and output_type=="GeoDataFrame":
                output_type = "GeoDataFrame"
                # Presumed to be a list of properties that possibly include coordinates
                geojson = {"type" : "FeatureCollection", "features" : []}
                for p in results:
                    feature = {"type" : "Feature", "properties" : p}
                    if "geolocation" in feature["properties"]:
                        geo = feature["properties"].pop("geolocation")
                        if list(geo.keys()) == ["human_address"]:
                            feature["geometry"] = {"type" : "Point", "coordinates" : (nan, nan)}  
                        elif "coordinates" in geo:
                            feature["geometry"] = geo
                        else:
                            feature["geometry"] = {"type" : "Point", "coordinates" : (float(geo["longitude"]), float(geo["latitude"]))}
                    elif "geocoded_column" in feature["properties"]:
                        feature["geometry"] = feature["properties"].pop("geocoded_column")
                    else:
                        feature["geometry"] = {"type" : "Point", "coordinates" : (nan, nan)} 
                    
                    geojson["features"].append(feature)

                if len(results)>0:
                    logger.debug("Geometry found. Contructing geopandas GeoDataFrame")
                    new_gdf = gpd.GeoDataFrame.from_features(geojson, crs=4326)
                        
                    if offset==start_offset:
                        df = new_gdf
                    else:
                        df = pd.concat([df, new_gdf], ignore_index=True)
            else:
                output_type = "DataFrame"
                rows = pd.DataFrame.from_records(results)
                if offset==start_offset:
                    df = pd.DataFrame(rows)
                else:
                    df = pd.concat([df, rows], ignore_index=True)

            offset += len(results)

            if show_pbar:
                bar.update()

            if len(df)>=nrows:
                break
        
        return df, output_type
    

    def __date_format_search(self, start_date, stop_date):
        check_meta = True
        try:
            # Check if date is formatted as a date or is text that needs to be handled more carefully
            meta = self.client.get_metadata(self.data_set)
        except (requests.HTTPError, requests.ConnectionError) as e:
            raise OPD_SocrataHTTPError(self.url, self.data_set, *e.args, _url_error_msg.format(self.get_api_url()))
        except Exception as e:
            check_meta = False
            raise

        data_formats = set()
        if check_meta:
            column = [x for x in meta['columns'] if x['fieldName']==self.date_field]  # Extract date field
            if len(column)>0 and 'dataTypeName' in column[0]:
                if column[0]['dataTypeName']=='text':
                    if 'cachedContents' in column[0]:
                        data_formats = self.__get_formats_from_meta(column)
                    else:
                        raise ValueError(f'Unable to determine format of date column {self.date_field}')
                elif column[0]['dataTypeName']=='number':
                    if 'cachedContents' in column[0] and ('smallest' in column[0]['cachedContents'] or 'largest' in column[0]['cachedContents']):
                        if 'smallest' in column[0]['cachedContents'] and isinstance(column[0]['cachedContents']['smallest'],str) and \
                            column[0]['cachedContents']['smallest'].isdigit():
                            data_formats.add('YYYY')
                        if 'largest' in column[0]['cachedContents'] and isinstance(column[0]['cachedContents']['largest'],str) and \
                            column[0]['cachedContents']['largest'].isdigit():
                            data_formats.add('YYYY')
                        if len(data_formats)==0:
                            raise NotImplementedError()
                        return 'numeric', data_formats
                    else:
                        raise ValueError(f'Unable to determine format of date column {self.date_field}')
                else:  # This is a timestamp
                    return 'timestamp', None
                
        start_range, _, stop_range = datetime_parser.split_date_range(start_date, stop_date)
        if not start_range and not stop_range:
            return 'year', None
        
        for f in ['yyyymmdd', 'abbrev_month', 'MM/DD/YYYY']:
            if f not in data_formats:
                try:
                    if f=='yyyymmdd':
                        if self.__yyyymmdd_test():
                            data_formats.add(f)
                    elif f=='abbrev_month':
                        if self.__month_abbrev_test():
                            data_formats.add(f)
                    elif f=='MM/DD/YYYY':
                        if self.__mmddyyyy_test():
                            data_formats.add(f)
                    else:
                        raise NotImplementedError(f'Unknown data format {f}')
                except:
                    pass

        if len(data_formats)==0:
            raise NotImplementedError()
        
        return 'text', data_formats

    def __yyyymmdd_test(self):
        where = self.date_field + f" LIKE '20__-__-__%'"
        results = self.client.get(self.data_set, where=where,
                                limit=1, select=self.date_field)
        return len(results)>0
    
    def __mmddyyyy_test(self):
        # self.date_field + f" LIKE '{m}/_/{year}%' OR 
        where = f"{self.date_field} LIKE '_/_/20__%' OR {self.date_field} LIKE '__/_/20__%' OR " +\
            f"{self.date_field} LIKE '_/__/20__%' OR {self.date_field} LIKE '__/__/20__%'"
        results = self.client.get(self.data_set, where=where,
                                limit=1, select=self.date_field)
        return len(results)>0
    
    def __month_abbrev_test(self):
        where = f"{self.date_field} LIKE '20__ ___ _%'"
        results = self.client.get(self.data_set, where=where,
                                limit=1, select=self.date_field)

        return len(results)>0 and re.search(r'^\d{4}\s(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d{1,2}\b', results[0][self.date_field])

    def __get_formats_from_meta(self, column):
        formats = set()
        for key in ['largest', 'smallest']:
            if key in column[0]['cachedContents']:
                value = column[0]['cachedContents'][key]
                if isinstance(value, str):
                    value = value.strip()
                    if len(value)==0:
                        continue
                    if re.search(r'^\d{4}\-\d{2}\-\d{2}', value):
                        formats.add('yyyymmdd')  # This case case be handled using standard query
                    elif re.search(r'^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d+\s+\d{4}', value) or \
                        re.search(r'^\d{4}\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2}', value):
                        formats.add('abbrev_month')
                    elif re.search(r'^\d{1,2}/\d{1,2}/\d{4}\b', value):
                        formats.add('MM/DD/YYYY')
                    elif re.search(r'^\d{1,2}/\d{1,2}/[012]\d\b', value):
                        formats.add('MM/DD/YY')
                    elif re.search(r'^\d{4}\s*Q\d$', value):
                        formats.add('YYYY Q')
                    elif re.search(r'^\d{4}$', value):
                        formats.add('YYYY')
                    else:
                        raise NotImplementedError()
                else:
                    raise NotImplementedError()
            else:
                raise NotImplementedError()
            
        return formats