# the conda channel is included by default
channels:
  - defaults
  - esri
  - pypi
dependencies:
  - arcgis
  - geopandas
  - numpy
  - pandas
  - pyproj
  - requests
  - pip
  - pip:
    # regular pip packages
    -  sodapy